---
version: '3.6'
services:
  logstash_tdd:
    image: docker.elastic.co/logstash/logstash:${TAG:-6.4.1}
    container_name: logstash_tdd
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
    - ./files/:/files
    - ./files/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./files/configuration:/var/logstash/configuration
    - ./file-output:/var/logstash-file-output
    - ./go-server:/go-server
    expose:
    - "9001"
    ports:
    - "9001:9001"
    command:
    - sh
    - -c
    - /files/entrypoint.sh
